
# ROV Vision System Configuration

# Camera Settings
camera:
  width: 640
  height: 480
  fps: 30
  depth_units: 0.001  # meters

# YOLOv8 Model Settings
model:
  path: "yolov8n.pt"
  confidence_threshold: 0.5
  iou_threshold: 0.4
  target_classes: ["bottle", "cup", "person", "trash"]

# Servo Control Settings
servos:
  pan:
    pin: 9
    range: [-90, 90]
    center: 0
  tilt:
    pin: 10
    range: [-45, 45]
    center: 0
  gripper:
    pin: 11
    range: [0, 180]
    open: 90
    closed: 0

# Control Parameters
control:
  target_distance: 0.5      # meters
  grab_threshold: 0.1       # meters
  tracking_gain: 0.1        # proportional control gain
  max_speed: 50             # maximum servo speed

# Serial Communication
serial:
  port: "/dev/ttyUSB0"
  baudrate: 9600
  timeout: 1

# Safety Settings
safety:
  max_depth: 10.0           # meters
  emergency_surface: true
  collision_avoidance: true
